import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "./_components/ui/sonner"
import Footer from "./_components/footer"
import AuthProvider from "./_providers/auth"

// Configuração da fonte Inter do Google Fonts
const inter = Inter({ subsets: ["latin"] })

// Metadados para o documento
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Componente RootLayout que envolve a aplicação
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthProvider>
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <div className="my-4">
              <Footer />
            </div>
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
